# Copy this file to: scripts/release-config.ps1
# Then fill the values below.
# IMPORTANT: Keep scripts/release-config.ps1 private (it is gitignored).

$env:MODRINTH_TOKEN = "PASTE_MODRINTH_TOKEN_HERE"
$env:MODRINTH_PROJECT_ID = "PASTE_MODRINTH_PROJECT_ID_HERE"

$env:CURSEFORGE_TOKEN = "PASTE_CURSEFORGE_TOKEN_HERE"
$env:CURSEFORGE_PROJECT_ID = "PASTE_CURSEFORGE_PROJECT_ID_HERE"
$env:CURSEFORGE_MINECRAFT_VERSION = "1.21.11"
$env:CURSEFORGE_JAVA_VERSION = "Java 25"

# Optional overrides only if you want separate projects per loader:
# $env:MODRINTH_PROJECT_ID_FABRIC = "OPTIONAL_OVERRIDE"
# $env:MODRINTH_PROJECT_ID_FORGE = "OPTIONAL_OVERRIDE"
# $env:MODRINTH_PROJECT_ID_NEOFORGE = "OPTIONAL_OVERRIDE"
# $env:CURSEFORGE_PROJECT_ID_FABRIC = "OPTIONAL_OVERRIDE"
# $env:CURSEFORGE_PROJECT_ID_FORGE = "OPTIONAL_OVERRIDE"
# $env:CURSEFORGE_PROJECT_ID_NEOFORGE = "OPTIONAL_OVERRIDE"

# Optional: release | beta | alpha
# $env:RELEASE_TYPE = "release"
